name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: {}            # ← 手動実行も可（任意）

permissions:
  contents: write                  # ← gh-pages へ push する権限

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Create config.js file 📝
        working-directory: ./frontend
        run: |
          echo "const firebaseConfig = {" > config.js
          echo "  apiKey: '${{ secrets.VITE_FIREBASE_API_KEY }}'," >> config.js
          echo "  authDomain: '${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}'," >> config.js
          echo "  projectId: '${{ secrets.VITE_FIREBASE_PROJECT_ID }}'," >> config.js
          echo "  storageBucket: '${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}'," >> config.js
          echo "  messagingSenderId: '${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}'," >> config.js
          echo "  appId: '${{ secrets.VITE_FIREBASE_APP_ID }}'," >> config.js
          echo "};" >> config.js
          echo "const cloudFunctionUrl = '${{ secrets.VITE_CLOUDFUNCTION_URL }}';" >> config.js
          echo "--- verifying ---"
          ls -la config.js         # ← 実行（echo しない）

      # （任意・キャッシュ対策）コミットSHAでクエリを付与
      - name: Cache-bust script tag (optional)
        working-directory: ./frontend
        run: |
          SHORT=${GITHUB_SHA::7}
          sed -i "s|script\.js|script.js?v=$SHORT|g" index.html || true

      - name: Show files to deploy 🔍
        run: |
          echo "Commit: $GITHUB_SHA"
          ls -la frontend
          echo "---- script.js head ----"
          sed -n '1,20p' frontend/script.js || true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # 公開先
          folder: frontend          # 公開フォルダ（ビルドなし前提）
          clean: true               # 既存ファイルを掃除（重要）
          single-
